version: '2.2'
services:
  redis-singleton:
    image: redis:7.0
    container_name: redis-7.0
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    networks:
      - local-net

networks:
  local-net:
    external: true
